version: "3.8"
services:
  ocelotapigw_global:
    image: registry.cn-hangzhou.aliyuncs.com/laizhan/ocelotapigw:latest
    deploy:
      resources:
        limits:
          memory: 100m    
    container_name: ocelotapigw_global
    restart: always
    command: 
      # - dotnet dev-certs https --clean
      # - dotnet dev-certs https -ep /https/aspnetapp.pfx -p 6tcab0v39bb8
      # - dotnet dev-certs https --trust
      # - dotnet ZhanLai.OcelotApiGw.dll
    environment:
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=6tcab0v39bb8
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - /data/https:/https
    ports:
      - 80:80
      - 443:443
networks:
  default:
    name: zhanlai-network
    external: true