version: "3.8"
services:
  ocelotapigw_global:
    image: registry.cn-hangzhou.aliyuncs.com/laizhan/ocelotapigw:latest
    deploy:
      resources:
        limits:
          memory: 100m    
    container_name: ocelotapigw_global
    restart: always
    ports:
      - 10080:80
networks:
  default:
    name: zhanlai-network
    external: true