version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - 443:443
      - 80:80
    volumes:
      - /data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /data/https:/https
networks:
  default:
    name: zhanlai-network
    external: true


# docker rm nginx-1 -f && docker run --name nginx-1 -p 1080:80 -p 10443:443 -v /mnt/d/Downloads/zhanlai.net_nginx/zhanlai.net_nginx:/https -v /mnt/d/github_repositories/zhahlai.net.deploy/docker-compose/gateway/nginx/nginx.conf:/etc/nginx/nginx.conf -d nginx
# docker rm nginx-1 -f && docker run --name nginx-1 -d nginx

