version: '3.8'

services:

  ghost:
    image: ghost:latest
    restart: always
    ports:
      - 8080:2368
    container_name: ghost-server # suggestions: communication using container name in docker compose
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: http://zhanlai.net
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development

  db:
    image: mysql:8.0
    restart: always
    container_name: ghost-db # suggestions: communication using container name in docker compose
    environment:
      MYSQL_ROOT_PASSWORD: example

networks:
  default:
    name: zhanlai-network
    external: true